name: navigation
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.0

  favorite:
    path: ../features/favorite
  main_page:
    path: ../features/main_page
  home:
    path: ../features/home
  catalogue:
    path: ../features/catalogue
  detailed_dish_view:
    path: ../features/detailed_dish_view
  order_history:
    path: ../features/order_history
  settings:
    path: ../features/settings
  shopping_cart:
    path: ../features/shopping_cart

  core:
    path: ../core
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6

flutter:

