name: foood_delivery_app

description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  catalogue:
    path: ./features/catalogue
  home:
    path: ./features/home
  detailed_dish_view:
    path: ./features/detailed_dish_view
  core:
    path: ./core
  data:
    path: ./data
  navigation:
    path: ./navigation
  core_ui:
    path: ./core_ui
  settings:
    path: ./features/settings

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
  assets:
    - assets/pictures/


