name: main_page
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  favorite:
    path: ../favorite
  home:
    path: ../home
  order_history:
    path: ../order_history
  settings:
    path: ../settings
  shopping_cart:
    path: ../shopping_cart
  navigation:
    path: ../../navigation
  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  catalogue:
    path: ../catalogue
  detailed_dish_view:
    path: ../detailed_dish_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6

flutter:

