name: core
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  navigation:
    path: ../navigation
  get_it: ^7.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.0
  cloud_firestore: ^4.8.4
  auto_route: ^7.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

